### ISSUE TITLE
Navigate vim splits

### ISSUE THREAD

**Issue by maletor** [tmux-plugins/tmux-pain-control#13]
How are you using this to navigate with vim and tmux?

https://robots.thoughtbot.com/seamlessly-navigate-vim-and-tmux-splits

**Comment by ismay** [comment]
Use this plugin:

https://github.com/christoomey/vim-tmux-navigator

**Comment by bruno-** [comment]
Hi

> How are you using this to navigate with vim and tmux?

This plugin doesn't solve that problem. I think @ismay's suggestion is good.
