### ISSUE TITLE
Setting up new machine, repeat doesn't work anymore,  any ideas?

### ISSUE THREAD

**Issue by yifanchen** [tmux-plugins/tmux-pain-control#14]
Hi, I am setting up my new machine. Repeat in `prefix` + `shift` + `l`  and `prefix` + `shift` + `h` don't work anymore. I believe I have the same `.tmux.conf` on another machine and it works there. Any ideas?

**Comment by yifanchen** [comment]
I actually don't think `repeat` works anymore, now it is stopped working on both of my machines. Please confirm.

**Comment by jelohe** [comment]
Have you tried setting a `repeat-time` greater than 0? 
It works for me when i set it to 500 for example, but doesn't work when it's 0.

**Comment by yifanchen** [comment]
Oh yeah, that fixed it. Thanks a lot.
