### ISSUE TITLE
Idea: Swap panes

### ISSUE THREAD

**Issue by Industrial** [tmux-plugins/tmux-pain-control#15]
Hi!

I found this (and TPM) today and I'm loving it!

There's one thing I'd really like to have; being able to swap panes within a window. Is this possible?

gr,

Tom

**Comment by felixleong** [comment]
There's `Prefix` + `Ctrl-o` to rotate the panes around.

**Comment by bruno-** [comment]
> I found this (and TPM) today and I'm loving it!

Good to hear, thanks!

As @felixleong stated, there's already `prefix + ctrl-o` for that.
