### ISSUE TITLE
Repeatable?

### ISSUE THREAD

**Issue by babenzele** [tmux-plugins/tmux-pain-control#23]
You say **Resizing panes** is `repeatable`, what does that mean here? I can repeat on **Navigation** commands, but that's because I can keep `ctrl` pressed since my prefix is `ctrl + a`.

**Comment by bruno-** [comment]
Hey,

let's say you're resizing a pane with `prefix + K`. Pressing `prefix + K, K, K` (repeating just the key `K` without the prefix) will resize a pane multiple time.

**Comment by JoeSchr** [comment]
Came here to ask the same! That's a really nice feature, maybe add this part to the readme:

> let's say you're resizing a pane with prefix + K. Pressing prefix + K, K, K (repeating just the key K without the prefix) will resize a pane multiple time.

great work, love your plugins!
