### ISSUE TITLE
Why not use Vim standard pane splitting shortcuts?

### ISSUE THREAD

**Issue by adriangrigore** [tmux-plugins/tmux-pain-control#6]
Why not use prefix + v and prefix + s for splitting panes?

**Comment by aleprovencio** [comment]
@bruno- I agree with you but dont't you think using tmux-sessionist's `prefix + g` makes `prefix + s` less relevant? In addiction, if you're aiming for a more "unified" workflow, the current mappings are harder to transpose to vim than the inverse following @adriangrigore suggestion. Maybe we deserve at least an option? =)

**Comment by bruno-** [comment]
@aleprovencio, fair enough, I think an option would do. Wanna open a pull request?

**Comment by aleprovencio** [comment]
Sure, there you go: https://github.com/tmux-plugins/tmux-pain-control/pull/9
