### ISSUE TITLE
send-keys not working for C-l

### ISSUE THREAD

**Issue by jondkinney** [tmux-plugins/tmux-pain-control#7]
Hi there,

I have this setting:

```
# allow clearing of screen in a shell
bind C-l send-keys 'C-l'
```

Which allows me to hit `C-a-l` which is prefix, then hold down control and press lower case L. It's supposed to do the default thing that ctrl-l does and clear the screen. I'm not sure exactly what in tmux-sensible is blocking that, but I get navigated to the right pane instead of it doing the intended thing. 

Before I had tmux-sensible installed I did have the same settings it has to navigate splits by prefix h,j,k,l so I know there is a way to have the two co-exist.

If you have any ideas that'd be much appreciated. Thanks!

**Comment by jondkinney** [comment]
So ultimately what I did to fix this for me locally is to just put 

```
# allow clearing of screen in a shell
bind C-l send-keys 'C-l'
```

At the end of my `~/.tmux.conf` file so that it overrides whatever in the plugins is breaking it.

**Comment by bruno-** [comment]
Sorry for the late response.

This plugin overrides the tmux default `C-l`. The reason for this is explained [here](https://github.com/tmux-plugins/tmux-pain-control/pull/8#issuecomment-71036599).

I agree this might not please everyone, but this plugin has a bit more character than `tmux-sensible`. Unless a large number of users is unhappy I'll leave it as is.

**Comment by bruno-** [comment]
The readme is now updated and `C-hjkl` key bindings are documented in an attempt to make things more clear.

**Comment by jondkinney** [comment]
@bruno- thanks for the response. To clarify my April 16th response, with putting that line at the end of my `~/.tmux.conf` I'm able to fully use tmux-pain-control as intended (holding down ctrl and navigating with h,j,k,l) `C-l` in that case does navigate me to the right as intended. But I can also clear the screen with `prefix-C-l`. I am, however, also using this https://github.com/christoomey/vim-tmux-navigator so IDK how that plays into this plugin vs my mapping at the end of the file, etc. I just wanted to post an update here to mention that having it all working together is possible :) Thanks!
